// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAN1z_tvr699hVzqxlKKi6LEY4dTvIbMTE',
    appId: '1:825286711080:web:7094d1d3c4acae29be221d',
    messagingSenderId: '825286711080',
    projectId: 'nectere-homepage',
    authDomain: 'nectere-homepage.firebaseapp.com',
    storageBucket: 'nectere-homepage.appspot.com',
    measurementId: 'G-882XLYD7BF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeID6vwO6Oez9FRxTOsIGjPLSj94W3_zU',
    appId: '1:825286711080:android:dc0264269881b1f1be221d',
    messagingSenderId: '825286711080',
    projectId: 'nectere-homepage',
    storageBucket: 'nectere-homepage.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwAqUraZvPlxXlkQS-sQNYP5n3OIVQqHg',
    appId: '1:825286711080:ios:ef15c288aaf090b0be221d',
    messagingSenderId: '825286711080',
    projectId: 'nectere-homepage',
    storageBucket: 'nectere-homepage.appspot.com',
    iosClientId: '825286711080-6nubj811tjhofop94c77tg83seknuqpr.apps.googleusercontent.com',
    iosBundleId: 'jp.nectere.photoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwAqUraZvPlxXlkQS-sQNYP5n3OIVQqHg',
    appId: '1:825286711080:ios:ef15c288aaf090b0be221d',
    messagingSenderId: '825286711080',
    projectId: 'nectere-homepage',
    storageBucket: 'nectere-homepage.appspot.com',
    iosClientId: '825286711080-6nubj811tjhofop94c77tg83seknuqpr.apps.googleusercontent.com',
    iosBundleId: 'jp.nectere.photoapp',
  );
}
